apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtest-admin-app-deployment
  namespace: vtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vtest-admin-app
  template:
    metadata:
      labels:
        app: vtest-admin-app
    spec:
      containers:
      - name: vtest-admin-app
        image: kathiravan007/vtest-admin-app:3e2055a6055d7d013c86a8944a507de0c1c31aaa
        ports:
        - containerPort: 80 # Change to the port your app listens to
---
apiVersion: v1
kind: Service
metadata:
  name: vtest-admin-app-service
  namespace: vtest
spec:
  type: NodePort
  selector:
    app: vtest-admin-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007 # Change this if needed
