name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "Kathiravan@007" | docker login -u "kathiravan007" --password-stdin

      # Step 4: Build Docker image with dynamic tag (using GITHUB_SHA)
      - name: Build Docker image
        run: |
          docker build -t kathiravan007/vtest-app:${{ github.sha }} .

      # Step 5: Push Docker image
      - name: Push Docker image
        run: |
          docker push kathiravan007/vtest-app:${{ github.sha }}

      # Step 6: Update Deployment.yaml with new image tag
      - name: Update Deployment.yaml with new image tag
        run: |
          # Replace the image tag in Deployment.yaml with the new one
          sed -i 's|image: kathiravan007/vtest-admin-app:latest|image: kathiravan007/vtest-admin-app:${{ github.sha }}|' Deployment-files/Deployment.yaml
          
          # Commit and push changes to the repository using GITHUB_TOKEN
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Deployment-files/Deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }} in Deployment.yaml"
          
          # Use GITHUB_TOKEN for authentication
          git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/Kathiravan-cloud/Vtestadmin.git
