name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "Kathiravan@007" | docker login -u "kathiravan007" --password-stdin

      # Step 4: Build Docker image with dynamic tag (using GITHUB_SHA)
      - name: Build Docker image
        run: |
          docker build -t kathiravan007/vtest-app:${{ github.sha }} .

      # Step 5: Push Docker image
      - name: Push Docker image
        run: |
          docker push kathiravan007/vtest-app:${{ github.sha }}
